Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,6 +59,15 @@ jobs:
       - name: Release check
         if: github.event.inputs.release == 'true'
         run: |
+          if [[ "${{ secrets.STORE_FILE }}" == "" ]]; then
+            echo -e "\nERROR!\nリリースするには､ 署名鍵を設定する必要があります｡\n"
+            echo "STORE_FILE: JKS形式の署名鍵をBase64でエンコードした文字列"
+            echo "STORE_PASSWORD: キーストアのパスワード"
+            echo "KEY_ALIAS: 署名のエイリアス"
+            echo "KEY_PASSWORD: 署名のパスワード"
+            echo ""
+            exit 1
+          fi
           if [[ "${{ steps.check-tag.outputs.exists }}" == "true" ]]; then
             echo -e "\nERROR!\n既に同じタグが存在します｡\n"
             echo "build.gradle の versionName を変更してください"
